language: go

go:
  - 1.9
  
branches:
  only:
    - master

notifications:
  email: false

before_install:
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - go test ./...
  # - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="barito-flow.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi
  - go build baritoflow
  - ls # debug purpose

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - baritoflow
  on:
    tags: true
      
      
