language: go

go:
  - 1.9
  
branches:
  only:
    - master

notifications:
  email: false

install:
  - # skip

script:
  - go test ./...
  - GOOS=linux GOARCH=arm go build -o barito-flow-linux
  - GOOS=darwin GOARCH=arm go build -o barito-flow-darwin
  - ls # debug purpose

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - barito-flow-linux
    - barito-flow-darwin
  on:
    tags: true
      
      
