language: go

go:
  - 1.9
  
branches:
  only:
    - master

notifications:
  email: false

script:
  - go test ./...
  - go build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: barito-flow
  skip_cleanup: true
  on:
      tags: true
